#!/bin/bash

########## settings

levels=10
iface=/sys/class/backlight/intel_backlight/
msgdir=/run/logbrightnessd

########## defaults

factor=$(echo "$(cat $iface/max_brightness)/(2^$levels)" | bc -l)

########## functions

quit() {
    rm -rf $msgdir;
    echo $(cat $iface/max_brightness) > $iface/brightness
    echo "brightness has been reset to max"
}

########## setup

[ -d $msgdir ] && echo "logbrightnessd folder already exists in /tmp/" && exit 1
if [ $EUID = 0 ]; then
    chmod g+r $iface/brightness
else
    echo "this script must be run as root"
    exit 1
fi
shopt -s dotglob # just in case people try to spam $msgdir with dotfiles
mkdir -p $msgdir
chmod a+rwx $msgdir
echo $(cat $iface/max_brightness) > $iface/brightness
echo 10 > $msgdir/current_brightness

########## logbrightnessd

trap quit SIGINT SIGTERM
rm -rf $msgdir/*
while inotifywait -q -e CREATE $msgdir > /dev/null; do
    for f in $msgdir/*; do
        level=${f##*/}
        if ! [ "$level" = "current_brightness" ]; then # ignore the "log"
            rm -rf $f
            if [ "$level" -eq "$level" ] 2>/dev/null; then # only integers
                level=$([ $level -lt 0 ] && echo 0 || \
                    [ $level -gt $levels ] && echo $levels || \
                    echo $level)
                echo "(2^$(echo $level | awk '{printf $1}'))*$factor" | \
                     bc | cut -d "." -f1 > $iface/brightness
                echo $level > $msgdir/current_brightness
                echo "changed brightness to $level"
            fi
        fi
    done
done
